### ISSUE TITLE
DEADLINE_EXCEEDED on empty queue

### ISSUE THREAD

**Issue by RobertAtomic** [GoogleCloudPlatform/psq#21]
Hi,

It seems that if there are no tasks in the queue psqworker crashes after approximately 5 minutes with 

> google.gax.errors.GaxError: GaxError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>)

it seems that this is caused by https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2574

As far as I can tell there's no way to catch this exception in user supplied code so it renders psqworker unusable in a situation where there may be an empty queue.

Here's the stack trace in case it's helpful:

`Traceback (most recent call last):
  File "/usr/local/bin/psqworker", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psq/psqworker.py", line 116, in main
    worker.listen()
  File "/usr/local/lib/python2.7/dist-packages/psq/worker.py", line 94, in listen
    super(MultiprocessWorker, self).listen()
  File "/usr/local/lib/python2.7/dist-packages/psq/worker.py", line 53, in listen
    tasks = self._safe_dequeue()
  File "/usr/local/lib/python2.7/dist-packages/psq/worker.py", line 46, in _safe_dequeue
    return inner()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/psq/worker.py", line 45, in inner
    return self.queue.dequeue(max=self.tasks_per_poll, block=True)
  File "/usr/local/lib/python2.7/dist-packages/psq/queue.py", line 104, in dequeue
    return_immediately=not block, max_messages=max)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/subscription.py", line 328, in pull
    self.full_name, return_immediately, max_messages)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/_gax.py", line 414, in subscription_pull
    return_immediately=return_immediately)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/pubsub/v1/subscriber_api.py", line 545, in pull
    return self._pull(request, options)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 481, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 469, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 434, in inner
    errors.create_error('RPC failed', cause=exception))
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 430, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 64, in inner
    return a_func(*updated_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
google.gax.errors.GaxError: GaxError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>)
E1208 20:06:37.135646157   14219 network_status_tracker.c:48] Memory leaked as all network endpoints were not shut down`

**Comment by jonparrott** [comment]
I believe this has been fixed upstream in google-cloud-python.

Can you confirm your library versions with "pip freeze"?

**Comment by RobertAtomic** [comment]
google-cloud==0.21.1
google-cloud-pubsub==0.21.0

I tried `pip install --upgrade git+https://github.com/GoogleCloudPlatform/google-cloud-python.git`
but still wasn't able to resolve the issue.

**Comment by jonparrott** [comment]
great, thanks. @dhermes I thought that pub/sub was catching and ignoring DEADLINE_EXCEEDED errors during pull now?

**Comment by dhermes** [comment]
No release yet. Running

```
pip install --upgrade git+https://github.com/GoogleCloudPlatform/google-cloud-python.git
```

will just install the base [`setup.py`][1] which is just a collection of PyPI packages.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6b93d4066fd85a1f9b56fd10baa5aec6e844f9e5/setup.py

**Comment by jonparrott** [comment]
@dhermes but it will indeed be in the next release?

**Comment by dhermes** [comment]
Yes hopefully today

**Comment by jonparrott** [comment]
Thanks, I'm gonna close this. @RobertAtomic look out for the next release. :)
